name: evaluacion3_4
description: "A new Flutter project."
publish_to: 'none'  # Elimina esta línea si deseas publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.0.0
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  audioplayers: ^0.20.0

  googleapis: ^10.0.0
  googleapis_auth: ^1.0.0
  path_provider: ^2.0.3
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
