// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB502wvk3wSsdnWSl9dKMfm-E3bseBz2eg',
    appId: '1:474193266928:web:5bc54ec7ad2f0397fdda35',
    messagingSenderId: '474193266928',
    projectId: 'evaluacion3-appmoviles-3e8c0',
    authDomain: 'evaluacion3-appmoviles-3e8c0.firebaseapp.com',
    storageBucket: 'evaluacion3-appmoviles-3e8c0.firebasestorage.app',
    measurementId: 'G-0YZMNW50MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQeb4tjw9iahmbZ7pMEbKQAXj16T2Ye0',
    appId: '1:474193266928:android:25943176a9cb4166fdda35',
    messagingSenderId: '474193266928',
    projectId: 'evaluacion3-appmoviles-3e8c0',
    storageBucket: 'evaluacion3-appmoviles-3e8c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFhEHMzLaDUwENN5TfFlqf1CNZJsjxGwU',
    appId: '1:474193266928:ios:39e775d62fef979efdda35',
    messagingSenderId: '474193266928',
    projectId: 'evaluacion3-appmoviles-3e8c0',
    storageBucket: 'evaluacion3-appmoviles-3e8c0.firebasestorage.app',
    iosBundleId: 'com.example.evaluacion34',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFhEHMzLaDUwENN5TfFlqf1CNZJsjxGwU',
    appId: '1:474193266928:ios:39e775d62fef979efdda35',
    messagingSenderId: '474193266928',
    projectId: 'evaluacion3-appmoviles-3e8c0',
    storageBucket: 'evaluacion3-appmoviles-3e8c0.firebasestorage.app',
    iosBundleId: 'com.example.evaluacion34',
  );
}
